[package]
name = "hexspec"
version = "0.1.1"
edition = "2021"

description = "A dsl for creating and verifying byte buffers"
license-file = "../LICENSE"
repository = "https://github.com/felgenh3/hexspec"

[dependencies]
nom = "7.1"
nom_locate = "4.0"
thiserror = "1.0"

